name: kjv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  clipboard: ^0.1.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  get: ^4.6.6
  provider: ^6.1.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/